//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题目,A,B,答案
        ///“君子之言，信而有征”最早出现在《论语》。( ),A:对,B:不对,B
        ///每月还款时多存入一定金额现金可以保证足额还款，应付出差、利率上调等特殊情况，避免造成不良信用记录。( ),A:对,B:不对,A
        ///有助学贷款的同学，逾期不还且不与高校联系（或虽联系但协商未果）者，其违约信息将进入中国人民银行个人征信系统、教育部大学生学历查询系统等社会征信系统，这样会对违约者以后的工作、生活造成重大影响。( ),A:对,B:不对,A
        ///国家助学贷款信息也属于个人信息基础数据库的征集范围。( ),A:对,B:不对,A
        ///高校助学贷款学生办理贴息延期手续必须是毕业当年考入更高层次学历就读（  ）,A:对,B:不对,A
        /// 韦同学毕业后应征入伍获学费补偿24000元，而他在校期间获得国家助学贷款20000元，因现在家庭生意周转存在困难，向学校提出先还贷款10000元，剩余14000元发给学生用于救急，以后赚钱了个人再还贷款本息。( ),A:对,B:不对,B
        ///各县学生资助管理部门应及时发放户籍为本县的应征入伍服义务兵役毕业生的补偿代偿经费。对于未还清生源地助学贷款的，催促其偿还贷款。( ),A:对,B:不 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string subjects {
            get {
                return ResourceManager.GetString("subjects", resourceCulture);
            }
        }
    }
}
